/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookappointmentRouteImport } from './routes/bookappointment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrigaidearIndexRouteImport } from './routes/brigaidear/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BrigaidearVideosRouteImport } from './routes/brigaidear/videos'
import { Route as BrigaidearReviewsRouteImport } from './routes/brigaidear/reviews'
import { Route as BrigaidearLoginRouteImport } from './routes/brigaidear/login'
import { Route as BrigaidearDashboardRouteImport } from './routes/brigaidear/dashboard'
import { Route as BrigaidearContactRouteImport } from './routes/brigaidear/contact'
import { Route as BrigaidearBookappointmentRouteImport } from './routes/brigaidear/bookappointment'
import { Route as BrigaidearBlogsRouteImport } from './routes/brigaidear/blogs'
import { Route as BrigaidearLayoutRouteImport } from './routes/brigaidear/_layout'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as AdminVideosRouteImport } from './routes/admin/videos'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookappointmentRoute = BookappointmentRouteImport.update({
  id: '/bookappointment',
  path: '/bookappointment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrigaidearIndexRoute = BrigaidearIndexRouteImport.update({
  id: '/brigaidear/',
  path: '/brigaidear/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrigaidearVideosRoute = BrigaidearVideosRouteImport.update({
  id: '/brigaidear/videos',
  path: '/brigaidear/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const BrigaidearReviewsRoute = BrigaidearReviewsRouteImport.update({
  id: '/brigaidear/reviews',
  path: '/brigaidear/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const BrigaidearLoginRoute = BrigaidearLoginRouteImport.update({
  id: '/brigaidear/login',
  path: '/brigaidear/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BrigaidearDashboardRoute = BrigaidearDashboardRouteImport.update({
  id: '/brigaidear/dashboard',
  path: '/brigaidear/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrigaidearContactRoute = BrigaidearContactRouteImport.update({
  id: '/brigaidear/contact',
  path: '/brigaidear/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrigaidearBookappointmentRoute =
  BrigaidearBookappointmentRouteImport.update({
    id: '/brigaidear/bookappointment',
    path: '/brigaidear/bookappointment',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrigaidearBlogsRoute = BrigaidearBlogsRouteImport.update({
  id: '/brigaidear/blogs',
  path: '/brigaidear/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const BrigaidearLayoutRoute = BrigaidearLayoutRouteImport.update({
  id: '/brigaidear/_layout',
  path: '/brigaidear',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/admin/videos',
  path: '/admin/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookappointment': typeof BookappointmentRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/brigaidear': typeof BrigaidearLayoutRoute
  '/brigaidear/blogs': typeof BrigaidearBlogsRoute
  '/brigaidear/bookappointment': typeof BrigaidearBookappointmentRoute
  '/brigaidear/contact': typeof BrigaidearContactRoute
  '/brigaidear/dashboard': typeof BrigaidearDashboardRoute
  '/brigaidear/login': typeof BrigaidearLoginRoute
  '/brigaidear/reviews': typeof BrigaidearReviewsRoute
  '/brigaidear/videos': typeof BrigaidearVideosRoute
  '/admin/': typeof AdminIndexRoute
  '/brigaidear/': typeof BrigaidearIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookappointment': typeof BookappointmentRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/brigaidear': typeof BrigaidearIndexRoute
  '/brigaidear/blogs': typeof BrigaidearBlogsRoute
  '/brigaidear/bookappointment': typeof BrigaidearBookappointmentRoute
  '/brigaidear/contact': typeof BrigaidearContactRoute
  '/brigaidear/dashboard': typeof BrigaidearDashboardRoute
  '/brigaidear/login': typeof BrigaidearLoginRoute
  '/brigaidear/reviews': typeof BrigaidearReviewsRoute
  '/brigaidear/videos': typeof BrigaidearVideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookappointment': typeof BookappointmentRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/brigaidear/_layout': typeof BrigaidearLayoutRoute
  '/brigaidear/blogs': typeof BrigaidearBlogsRoute
  '/brigaidear/bookappointment': typeof BrigaidearBookappointmentRoute
  '/brigaidear/contact': typeof BrigaidearContactRoute
  '/brigaidear/dashboard': typeof BrigaidearDashboardRoute
  '/brigaidear/login': typeof BrigaidearLoginRoute
  '/brigaidear/reviews': typeof BrigaidearReviewsRoute
  '/brigaidear/videos': typeof BrigaidearVideosRoute
  '/admin/': typeof AdminIndexRoute
  '/brigaidear/': typeof BrigaidearIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookappointment'
    | '/contact'
    | '/education'
    | '/reviews'
    | '/services'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/reviews'
    | '/admin/videos'
    | '/blogs/$slug'
    | '/brigaidear'
    | '/brigaidear/blogs'
    | '/brigaidear/bookappointment'
    | '/brigaidear/contact'
    | '/brigaidear/dashboard'
    | '/brigaidear/login'
    | '/brigaidear/reviews'
    | '/brigaidear/videos'
    | '/admin/'
    | '/brigaidear/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookappointment'
    | '/contact'
    | '/education'
    | '/reviews'
    | '/services'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/reviews'
    | '/admin/videos'
    | '/blogs/$slug'
    | '/brigaidear'
    | '/brigaidear/blogs'
    | '/brigaidear/bookappointment'
    | '/brigaidear/contact'
    | '/brigaidear/dashboard'
    | '/brigaidear/login'
    | '/brigaidear/reviews'
    | '/brigaidear/videos'
  id:
    | '__root__'
    | '/'
    | '/bookappointment'
    | '/contact'
    | '/education'
    | '/reviews'
    | '/services'
    | '/admin/_layout'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/reviews'
    | '/admin/videos'
    | '/blogs/$slug'
    | '/brigaidear/_layout'
    | '/brigaidear/blogs'
    | '/brigaidear/bookappointment'
    | '/brigaidear/contact'
    | '/brigaidear/dashboard'
    | '/brigaidear/login'
    | '/brigaidear/reviews'
    | '/brigaidear/videos'
    | '/admin/'
    | '/brigaidear/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookappointmentRoute: typeof BookappointmentRoute
  ContactRoute: typeof ContactRoute
  EducationRoute: typeof EducationRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminVideosRoute: typeof AdminVideosRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  BrigaidearLayoutRoute: typeof BrigaidearLayoutRoute
  BrigaidearBlogsRoute: typeof BrigaidearBlogsRoute
  BrigaidearBookappointmentRoute: typeof BrigaidearBookappointmentRoute
  BrigaidearContactRoute: typeof BrigaidearContactRoute
  BrigaidearDashboardRoute: typeof BrigaidearDashboardRoute
  BrigaidearLoginRoute: typeof BrigaidearLoginRoute
  BrigaidearReviewsRoute: typeof BrigaidearReviewsRoute
  BrigaidearVideosRoute: typeof BrigaidearVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BrigaidearIndexRoute: typeof BrigaidearIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookappointment': {
      id: '/bookappointment'
      path: '/bookappointment'
      fullPath: '/bookappointment'
      preLoaderRoute: typeof BookappointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brigaidear/': {
      id: '/brigaidear/'
      path: '/brigaidear'
      fullPath: '/brigaidear/'
      preLoaderRoute: typeof BrigaidearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brigaidear/videos': {
      id: '/brigaidear/videos'
      path: '/brigaidear/videos'
      fullPath: '/brigaidear/videos'
      preLoaderRoute: typeof BrigaidearVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brigaidear/reviews': {
      id: '/brigaidear/reviews'
      path: '/brigaidear/reviews'
      fullPath: '/brigaidear/reviews'
      preLoaderRoute: typeof BrigaidearReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brigaidear/login': {
      id: '/brigaidear/login'
      path: '/brigaidear/login'
      fullPath: '/brigaidear/login'
      preLoaderRoute: typeof BrigaidearLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brigaidear/dashboard': {
      id: '/brigaidear/dashboard'
      path: '/brigaidear/dashboard'
      fullPath: '/brigaidear/dashboard'
      preLoaderRoute: typeof BrigaidearDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brigaidear/contact': {
      id: '/brigaidear/contact'
      path: '/brigaidear/contact'
      fullPath: '/brigaidear/contact'
      preLoaderRoute: typeof BrigaidearContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brigaidear/bookappointment': {
      id: '/brigaidear/bookappointment'
      path: '/brigaidear/bookappointment'
      fullPath: '/brigaidear/bookappointment'
      preLoaderRoute: typeof BrigaidearBookappointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brigaidear/blogs': {
      id: '/brigaidear/blogs'
      path: '/brigaidear/blogs'
      fullPath: '/brigaidear/blogs'
      preLoaderRoute: typeof BrigaidearBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brigaidear/_layout': {
      id: '/brigaidear/_layout'
      path: '/brigaidear'
      fullPath: '/brigaidear'
      preLoaderRoute: typeof BrigaidearLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/admin/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookappointmentRoute: BookappointmentRoute,
  ContactRoute: ContactRoute,
  EducationRoute: EducationRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  AdminLayoutRoute: AdminLayoutRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminVideosRoute: AdminVideosRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  BrigaidearLayoutRoute: BrigaidearLayoutRoute,
  BrigaidearBlogsRoute: BrigaidearBlogsRoute,
  BrigaidearBookappointmentRoute: BrigaidearBookappointmentRoute,
  BrigaidearContactRoute: BrigaidearContactRoute,
  BrigaidearDashboardRoute: BrigaidearDashboardRoute,
  BrigaidearLoginRoute: BrigaidearLoginRoute,
  BrigaidearReviewsRoute: BrigaidearReviewsRoute,
  BrigaidearVideosRoute: BrigaidearVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
  BrigaidearIndexRoute: BrigaidearIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
